node {
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/raosatish/Diety.git'
   }
   stage('Build') {
         bat "dotnet restore --source http://raosystemsinc-1/MyNuget/nuget/ --source https://api.nuget.org/v3/index.json"
         bat "dotnet build"
   }
}